### ISSUE TITLE
Installation of ASTERIA failed locally and on cobalt cluster with python 3.10

### ISSUE THREAD

**Issue by jakob2508** [icecube/ASTERIA#80]
First tried to install ASTERIA locally with Python 3.8.10:
$ python setup.py install
Failed to install SNEWPY dependency, possibly due to prior installations

Tried to created virtual python environment.
$ python3 -m venv ./venv_asteria
Failed as virtual environment not installed.

Tried to install virtual environmnet.
$ sudo apt install python3.8-venv
> libc-bin
  E: Sub-process /usr/bin/dpkg returned an error code (1)

Then switched to the cobalt nodes and installed virtual environment.
$ python3 -m venv ./venv_asteria
and activated virtual environment. Configured preinstalled git and cloned ASTERIA repository with HTTPS.
$ git clone https://github.com/icecube/ASTERIA.git
Moved to ASTERIA directory and tried to install program
$ python setup.py install
> Traceback (most recent call last):
  File "setup.py", line 35, in <module>
    setup_keywords['long_description'] = readme.read()
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 230: ordinal not in range(128)

deactivate and remote virtual environment and execute
$ eval `/cvmfs/icecube.opensciencegrid.org/py3-v4.2.0/setup.sh`
Python version 3.10.2, reinstall virtual environment and run
$ python setup.py install
> Traceback (most recent call last):
  File "/home/jbeise/venv_asteria/lib/python3.10/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/home/jbeise/venv_asteria/lib/python3.10/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/jbeise/venv_asteria/lib/python3.10/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/home/jbeise/venv_asteria/lib/python3.10/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-u7twgl84/tables-3.8.0/setup.py", line 20, in <module>
    setup_keywords = dict()
ModuleNotFoundError: No module named 'packaging'

**Comment by sybenzvi** [comment]
I'm going to close this out as we now have extensive build tests for Python 3.10 - 3.13, including ubuntu, Mac OS, and Windows.
